# 服务端口
server:
  port: 8888

# Spring配置
spring:

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/DB_OnlineStoreSys?serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 123456

  servlet:
    multipart:
      # 最大文件传输大小
      max-file-size: 30MB

  # Redis
  redis:
    database: 0
    host: redis
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#是否开启推荐算法
useRecommend: false
